name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install the JVM
      run: sudo apt-get install default-jdk
    - name: Install Firtool
      run: |
           wget -q -O - https://github.com/llvm/circt/releases/download/firtool-1.38.0/firrtl-bin-ubuntu-20.04.tar.gz | tar -zx
           echo "$GITHUB_WORKSPACE/firtool-1.38.0/bin" >> $GITHUB_PATH
    - name: Build
      run: sbt run
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Trinity.sv
        path: generated/Trinity.sv
