# Copyright (C) 2023 Alan Jian (alanjian85@outlook.com)
# SPDX-License-Identifier: MIT

name: Test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install the JVM
      run: sudo apt-get install default-jdk
    - name: Test
      run: sbt test
